[build]
command = "npm install && npm run build && npm run build:api && npm run start"
publish = "frontend/dist"

[build.environment]
NODE_VERSION = "22"
NPM_FLAGS = "--legacy-peer-deps"

[start]
run = "node api/dist/index.js"
