[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x']

[phases.install]
cmds = [
    'rm -rf node_modules package-lock.json lib',
    'npm install --legacy-peer-deps'
]

[phases.build]
cmds = [
    'npx turbo run build --filter=frontend --filter=docs --filter=api --no-daemon --output-logs=full --ui=stream --log-order=stream --concurrency=1'
]

[start]
cmd = 'npm run start'