[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x']

[phases.install]
cmds = [
    'rm -rf node_modules package-lock.json lib',
    'npm install --legacy-peer-deps'
]

[phases.build]
cmds = [
    'npx turbo run build'
]

[start]
cmd = 'npm run start'